package com.taoye.labor_dispatch.mapper;

import com.taoye.labor_dispatch.entity.IntialDescription;
import com.taoye.labor_dispatch.entity.IntialDescriptionExample;
import java.util.List;

import com.taoye.labor_dispatch.entity.dto.IntialDescriptionDto;
import com.taoye.labor_dispatch.entity.vo.IntialDescriptionVo;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface IntialDescriptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intial_description
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    long countByExample(IntialDescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intial_description
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    int deleteByExample(IntialDescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intial_description
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intial_description
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    int insert(IntialDescription row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intial_description
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    int insertSelective(IntialDescription row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intial_description
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    List<IntialDescription> selectByExample(IntialDescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intial_description
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    IntialDescription selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intial_description
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    int updateByExampleSelective(@Param("row") IntialDescription row, @Param("example") IntialDescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intial_description
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    int updateByExample(@Param("row") IntialDescription row, @Param("example") IntialDescriptionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intial_description
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    int updateByPrimaryKeySelective(IntialDescription row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intial_description
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    int updateByPrimaryKey(IntialDescription row);

    List<IntialDescriptionVo> query(IntialDescriptionDto dto);
}