package com.taoye.labor_dispatch.mapper;

import com.taoye.labor_dispatch.entity.TagDescriptionRef;
import com.taoye.labor_dispatch.entity.TagDescriptionRefExample;
import java.util.List;

import com.taoye.labor_dispatch.entity.vo.IntialDescriptionVo;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface TagDescriptionRefMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_description_ref
     *
     * @mbg.generated Wed Apr 15 15:39:06 CST 2026
     */
    long countByExample(TagDescriptionRefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_description_ref
     *
     * @mbg.generated Wed Apr 15 15:39:06 CST 2026
     */
    int deleteByExample(TagDescriptionRefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_description_ref
     *
     * @mbg.generated Wed Apr 15 15:39:06 CST 2026
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_description_ref
     *
     * @mbg.generated Wed Apr 15 15:39:06 CST 2026
     */
    int insert(TagDescriptionRef row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_description_ref
     *
     * @mbg.generated Wed Apr 15 15:39:06 CST 2026
     */
    int insertSelective(TagDescriptionRef row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_description_ref
     *
     * @mbg.generated Wed Apr 15 15:39:06 CST 2026
     */
    List<TagDescriptionRef> selectByExample(TagDescriptionRefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_description_ref
     *
     * @mbg.generated Wed Apr 15 15:39:06 CST 2026
     */
    TagDescriptionRef selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_description_ref
     *
     * @mbg.generated Wed Apr 15 15:39:06 CST 2026
     */
    int updateByExampleSelective(@Param("row") TagDescriptionRef row, @Param("example") TagDescriptionRefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_description_ref
     *
     * @mbg.generated Wed Apr 15 15:39:06 CST 2026
     */
    int updateByExample(@Param("row") TagDescriptionRef row, @Param("example") TagDescriptionRefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_description_ref
     *
     * @mbg.generated Wed Apr 15 15:39:06 CST 2026
     */
    int updateByPrimaryKeySelective(TagDescriptionRef row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_description_ref
     *
     * @mbg.generated Wed Apr 15 15:39:06 CST 2026
     */
    int updateByPrimaryKey(TagDescriptionRef row);

//    List<Long> query(List<String> tagInfoList);

    List<Long> queryByCodeList(@Param("tagInfoList")List<String> tagInfoList);

    Boolean deleteByDes(@Param("desId") Long id);

//    List<IntialDescriptionVo> query(@Param("id") Integer id , @Param("code") String code);
}