package com.taoye.labor_dispatch.mapper;

import com.taoye.labor_dispatch.entity.TagInfo;
import com.taoye.labor_dispatch.entity.TagInfoExample;
import java.util.List;

import com.taoye.labor_dispatch.entity.dto.TagInfoDto;
import com.taoye.labor_dispatch.entity.vo.TagInfoVo;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TagInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_info
     *
     * @mbg.generated Wed Apr 15 13:54:49 CST 2026
     */
    long countByExample(TagInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_info
     *
     * @mbg.generated Wed Apr 15 13:54:49 CST 2026
     */
    int deleteByExample(TagInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_info
     *
     * @mbg.generated Wed Apr 15 13:54:49 CST 2026
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_info
     *
     * @mbg.generated Wed Apr 15 13:54:49 CST 2026
     */
    int insert(TagInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_info
     *
     * @mbg.generated Wed Apr 15 13:54:49 CST 2026
     */
    int insertSelective(TagInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_info
     *
     * @mbg.generated Wed Apr 15 13:54:49 CST 2026
     */
    List<TagInfo> selectByExample(TagInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_info
     *
     * @mbg.generated Wed Apr 15 13:54:49 CST 2026
     */
    TagInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_info
     *
     * @mbg.generated Wed Apr 15 13:54:49 CST 2026
     */
    int updateByExampleSelective(@Param("row") TagInfo row, @Param("example") TagInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_info
     *
     * @mbg.generated Wed Apr 15 13:54:49 CST 2026
     */
    int updateByExample(@Param("row") TagInfo row, @Param("example") TagInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_info
     *
     * @mbg.generated Wed Apr 15 13:54:49 CST 2026
     */
    int updateByPrimaryKeySelective(TagInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_info
     *
     * @mbg.generated Wed Apr 15 13:54:49 CST 2026
     */
    int updateByPrimaryKey(TagInfo row);

    TagInfo query(@Param("code")String item);

    List<String> selectByUser(@Param("userId") Long id);

    List<String> selectCodeByUser(@Param("userId") Long id);

    List<String> selectByDes(@Param("desId") Long id);

    List<TagInfoVo> queryList(TagInfoDto tagInfoDto);

    List<String> selectCodeByDes(@Param("desId") Long id);
}