package com.taoye.labor_dispatch.mapper;

import com.taoye.labor_dispatch.entity.TagInfo;
import com.taoye.labor_dispatch.entity.TagInfoExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface TagInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_info
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    long countByExample(TagInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_info
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    int deleteByExample(TagInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_info
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_info
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    int insert(TagInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_info
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    int insertSelective(TagInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_info
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    List<TagInfo> selectByExample(TagInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_info
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    TagInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_info
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    int updateByExampleSelective(@Param("row") TagInfo row, @Param("example") TagInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_info
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    int updateByExample(@Param("row") TagInfo row, @Param("example") TagInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_info
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    int updateByPrimaryKeySelective(TagInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_info
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    int updateByPrimaryKey(TagInfo row);
}