package com.taoye.labor_dispatch.mapper;

import com.taoye.labor_dispatch.entity.TagUserInfoRef;
import com.taoye.labor_dispatch.entity.TagUserInfoRefExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TagUserInfoRefMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_user_info_ref
     *
     * @mbg.generated Wed Apr 15 15:10:00 CST 2026
     */
    long countByExample(TagUserInfoRefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_user_info_ref
     *
     * @mbg.generated Wed Apr 15 15:10:00 CST 2026
     */
    int deleteByExample(TagUserInfoRefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_user_info_ref
     *
     * @mbg.generated Wed Apr 15 15:10:00 CST 2026
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_user_info_ref
     *
     * @mbg.generated Wed Apr 15 15:10:00 CST 2026
     */
    int insert(TagUserInfoRef row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_user_info_ref
     *
     * @mbg.generated Wed Apr 15 15:10:00 CST 2026
     */
    int insertSelective(TagUserInfoRef row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_user_info_ref
     *
     * @mbg.generated Wed Apr 15 15:10:00 CST 2026
     */
    List<TagUserInfoRef> selectByExample(TagUserInfoRefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_user_info_ref
     *
     * @mbg.generated Wed Apr 15 15:10:00 CST 2026
     */
    TagUserInfoRef selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_user_info_ref
     *
     * @mbg.generated Wed Apr 15 15:10:00 CST 2026
     */
    int updateByExampleSelective(@Param("row") TagUserInfoRef row, @Param("example") TagUserInfoRefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_user_info_ref
     *
     * @mbg.generated Wed Apr 15 15:10:00 CST 2026
     */
    int updateByExample(@Param("row") TagUserInfoRef row, @Param("example") TagUserInfoRefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_user_info_ref
     *
     * @mbg.generated Wed Apr 15 15:10:00 CST 2026
     */
    int updateByPrimaryKeySelective(TagUserInfoRef row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_user_info_ref
     *
     * @mbg.generated Wed Apr 15 15:10:00 CST 2026
     */
    int updateByPrimaryKey(TagUserInfoRef row);

    TagUserInfoRef selectByCode(String item);
}