package com.taoye.labor_dispatch.entity.vo;

import java.util.Date;
import java.util.List;

/**
 * @author (taoye)  
 * @version V1.0 
 * @ClassName: IntialDescriptionVo 
 * @Description: TODO() 
 * @date 2026-04-14 22:38
 */
public class IntialDescriptionVo {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intial_description.id
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intial_description.intial_description
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    private String intialDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intial_description.wechat_number
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    private String wechatNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intial_description.create_time
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intial_description.update_time
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intial_description.is_delete
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    private Byte isDelete;
    private String groupAffiliation;

    private List<String> tagCodeList;

//    private List<Long> tagIdList;

    private List<String> tagNameList;

    private List<String> tagInfoList;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intial_description.id
     *
     * @return the value of intial_description.id
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intial_description.id
     *
     * @param id the value for intial_description.id
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intial_description.intial_description
     *
     * @return the value of intial_description.intial_description
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    public String getIntialDescription() {
        return intialDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intial_description.intial_description
     *
     * @param intialDescription the value for intial_description.intial_description
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    public void setIntialDescription(String intialDescription) {
        this.intialDescription = intialDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intial_description.wechat_number
     *
     * @return the value of intial_description.wechat_number
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    public String getWechatNumber() {
        return wechatNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intial_description.wechat_number
     *
     * @param wechatNumber the value for intial_description.wechat_number
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    public void setWechatNumber(String wechatNumber) {
        this.wechatNumber = wechatNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intial_description.create_time
     *
     * @return the value of intial_description.create_time
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intial_description.create_time
     *
     * @param createTime the value for intial_description.create_time
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intial_description.update_time
     *
     * @return the value of intial_description.update_time
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intial_description.update_time
     *
     * @param updateTime the value for intial_description.update_time
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intial_description.is_delete
     *
     * @return the value of intial_description.is_delete
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intial_description.is_delete
     *
     * @param isDelete the value for intial_description.is_delete
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }



    public List<String> getTagCodeList() {
        return tagCodeList;
    }

    public void setTagCodeList(List<String> tagCodeList) {
        this.tagCodeList = tagCodeList;
    }

    public String getGroupAffiliation() {
        return groupAffiliation;
    }

    public void setGroupAffiliation(String groupAffiliation) {
        this.groupAffiliation = groupAffiliation;
    }

    public List<String> getTagNameList() {
        return tagNameList;
    }

    public void setTagNameList(List<String> tagNameList) {
        this.tagNameList = tagNameList;
    }

    public List<String> getTagInfoList() {
        return tagInfoList;
    }

    public void setTagInfoList(List<String> tagInfoList) {
        this.tagInfoList = tagInfoList;
    }
}
