package com.taoye.labor_dispatch.entity.vo;

import java.util.Date;

public class TagInfoVo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_info.id
     *
     * @mbg.generated Wed Apr 15 13:54:49 CST 2026
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_info.tag_code
     *
     * @mbg.generated Wed Apr 15 13:54:49 CST 2026
     */
    private String tagCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_info.tag_name
     *
     * @mbg.generated Wed Apr 15 13:54:49 CST 2026
     */
    private String tagName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_info.create_time
     *
     * @mbg.generated Wed Apr 15 13:54:49 CST 2026
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_info.update_time
     *
     * @mbg.generated Wed Apr 15 13:54:49 CST 2026
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_info.is_delete
     *
     * @mbg.generated Wed Apr 15 13:54:49 CST 2026
     */
    private Byte isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_info.id
     *
     * @return the value of tag_info.id
     *
     * @mbg.generated Wed Apr 15 13:54:49 CST 2026
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_info.id
     *
     * @param id the value for tag_info.id
     *
     * @mbg.generated Wed Apr 15 13:54:49 CST 2026
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_info.tag_code
     *
     * @return the value of tag_info.tag_code
     *
     * @mbg.generated Wed Apr 15 13:54:49 CST 2026
     */
    public String getTagCode() {
        return tagCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_info.tag_code
     *
     * @param tagCode the value for tag_info.tag_code
     *
     * @mbg.generated Wed Apr 15 13:54:49 CST 2026
     */
    public void setTagCode(String tagCode) {
        this.tagCode = tagCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_info.tag_name
     *
     * @return the value of tag_info.tag_name
     *
     * @mbg.generated Wed Apr 15 13:54:49 CST 2026
     */
    public String getTagName() {
        return tagName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_info.tag_name
     *
     * @param tagName the value for tag_info.tag_name
     *
     * @mbg.generated Wed Apr 15 13:54:49 CST 2026
     */
    public void setTagName(String tagName) {
        this.tagName = tagName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_info.create_time
     *
     * @return the value of tag_info.create_time
     *
     * @mbg.generated Wed Apr 15 13:54:49 CST 2026
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_info.create_time
     *
     * @param createTime the value for tag_info.create_time
     *
     * @mbg.generated Wed Apr 15 13:54:49 CST 2026
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_info.update_time
     *
     * @return the value of tag_info.update_time
     *
     * @mbg.generated Wed Apr 15 13:54:49 CST 2026
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_info.update_time
     *
     * @param updateTime the value for tag_info.update_time
     *
     * @mbg.generated Wed Apr 15 13:54:49 CST 2026
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_info.is_delete
     *
     * @return the value of tag_info.is_delete
     *
     * @mbg.generated Wed Apr 15 13:54:49 CST 2026
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_info.is_delete
     *
     * @param isDelete the value for tag_info.is_delete
     *
     * @mbg.generated Wed Apr 15 13:54:49 CST 2026
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }
}