package com.taoye.labor_dispatch.entity;

import java.util.Date;

public class IntialDescription {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intial_description.id
     *
     * @mbg.generated Fri Apr 17 18:32:43 CST 2026
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intial_description.group_affiliation
     *
     * @mbg.generated Fri Apr 17 18:32:43 CST 2026
     */
    private String groupAffiliation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intial_description.wechat_number
     *
     * @mbg.generated Fri Apr 17 18:32:43 CST 2026
     */
    private String wechatNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intial_description.remark
     *
     * @mbg.generated Fri Apr 17 18:32:43 CST 2026
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intial_description.create_time
     *
     * @mbg.generated Fri Apr 17 18:32:43 CST 2026
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intial_description.update_time
     *
     * @mbg.generated Fri Apr 17 18:32:43 CST 2026
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intial_description.is_delete
     *
     * @mbg.generated Fri Apr 17 18:32:43 CST 2026
     */
    private Byte isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intial_description.intial_description
     *
     * @mbg.generated Fri Apr 17 18:32:43 CST 2026
     */
    private String intialDescription;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intial_description.id
     *
     * @return the value of intial_description.id
     *
     * @mbg.generated Fri Apr 17 18:32:43 CST 2026
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intial_description.id
     *
     * @param id the value for intial_description.id
     *
     * @mbg.generated Fri Apr 17 18:32:43 CST 2026
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intial_description.group_affiliation
     *
     * @return the value of intial_description.group_affiliation
     *
     * @mbg.generated Fri Apr 17 18:32:43 CST 2026
     */
    public String getGroupAffiliation() {
        return groupAffiliation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intial_description.group_affiliation
     *
     * @param groupAffiliation the value for intial_description.group_affiliation
     *
     * @mbg.generated Fri Apr 17 18:32:43 CST 2026
     */
    public void setGroupAffiliation(String groupAffiliation) {
        this.groupAffiliation = groupAffiliation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intial_description.wechat_number
     *
     * @return the value of intial_description.wechat_number
     *
     * @mbg.generated Fri Apr 17 18:32:43 CST 2026
     */
    public String getWechatNumber() {
        return wechatNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intial_description.wechat_number
     *
     * @param wechatNumber the value for intial_description.wechat_number
     *
     * @mbg.generated Fri Apr 17 18:32:43 CST 2026
     */
    public void setWechatNumber(String wechatNumber) {
        this.wechatNumber = wechatNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intial_description.remark
     *
     * @return the value of intial_description.remark
     *
     * @mbg.generated Fri Apr 17 18:32:43 CST 2026
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intial_description.remark
     *
     * @param remark the value for intial_description.remark
     *
     * @mbg.generated Fri Apr 17 18:32:43 CST 2026
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intial_description.create_time
     *
     * @return the value of intial_description.create_time
     *
     * @mbg.generated Fri Apr 17 18:32:43 CST 2026
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intial_description.create_time
     *
     * @param createTime the value for intial_description.create_time
     *
     * @mbg.generated Fri Apr 17 18:32:43 CST 2026
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intial_description.update_time
     *
     * @return the value of intial_description.update_time
     *
     * @mbg.generated Fri Apr 17 18:32:43 CST 2026
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intial_description.update_time
     *
     * @param updateTime the value for intial_description.update_time
     *
     * @mbg.generated Fri Apr 17 18:32:43 CST 2026
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intial_description.is_delete
     *
     * @return the value of intial_description.is_delete
     *
     * @mbg.generated Fri Apr 17 18:32:43 CST 2026
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intial_description.is_delete
     *
     * @param isDelete the value for intial_description.is_delete
     *
     * @mbg.generated Fri Apr 17 18:32:43 CST 2026
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intial_description.intial_description
     *
     * @return the value of intial_description.intial_description
     *
     * @mbg.generated Fri Apr 17 18:32:43 CST 2026
     */
    public String getIntialDescription() {
        return intialDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intial_description.intial_description
     *
     * @param intialDescription the value for intial_description.intial_description
     *
     * @mbg.generated Fri Apr 17 18:32:43 CST 2026
     */
    public void setIntialDescription(String intialDescription) {
        this.intialDescription = intialDescription;
    }
}