package com.taoye.labor_dispatch.entity;

import java.util.Date;

public class TagUserInfoRef {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_user_info_ref.id
     *
     * @mbg.generated Wed Apr 15 15:10:00 CST 2026
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_user_info_ref.tag_code
     *
     * @mbg.generated Wed Apr 15 15:10:00 CST 2026
     */
    private String tagCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_user_info_ref.user_info_id
     *
     * @mbg.generated Wed Apr 15 15:10:00 CST 2026
     */
    private Long userInfoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_user_info_ref.create_time
     *
     * @mbg.generated Wed Apr 15 15:10:00 CST 2026
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_user_info_ref.update_time
     *
     * @mbg.generated Wed Apr 15 15:10:00 CST 2026
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_user_info_ref.is_delete
     *
     * @mbg.generated Wed Apr 15 15:10:00 CST 2026
     */
    private Byte isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_user_info_ref.id
     *
     * @return the value of tag_user_info_ref.id
     *
     * @mbg.generated Wed Apr 15 15:10:00 CST 2026
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_user_info_ref.id
     *
     * @param id the value for tag_user_info_ref.id
     *
     * @mbg.generated Wed Apr 15 15:10:00 CST 2026
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_user_info_ref.tag_code
     *
     * @return the value of tag_user_info_ref.tag_code
     *
     * @mbg.generated Wed Apr 15 15:10:00 CST 2026
     */
    public String getTagCode() {
        return tagCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_user_info_ref.tag_code
     *
     * @param tagCode the value for tag_user_info_ref.tag_code
     *
     * @mbg.generated Wed Apr 15 15:10:00 CST 2026
     */
    public void setTagCode(String tagCode) {
        this.tagCode = tagCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_user_info_ref.user_info_id
     *
     * @return the value of tag_user_info_ref.user_info_id
     *
     * @mbg.generated Wed Apr 15 15:10:00 CST 2026
     */
    public Long getUserInfoId() {
        return userInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_user_info_ref.user_info_id
     *
     * @param userInfoId the value for tag_user_info_ref.user_info_id
     *
     * @mbg.generated Wed Apr 15 15:10:00 CST 2026
     */
    public void setUserInfoId(Long userInfoId) {
        this.userInfoId = userInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_user_info_ref.create_time
     *
     * @return the value of tag_user_info_ref.create_time
     *
     * @mbg.generated Wed Apr 15 15:10:00 CST 2026
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_user_info_ref.create_time
     *
     * @param createTime the value for tag_user_info_ref.create_time
     *
     * @mbg.generated Wed Apr 15 15:10:00 CST 2026
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_user_info_ref.update_time
     *
     * @return the value of tag_user_info_ref.update_time
     *
     * @mbg.generated Wed Apr 15 15:10:00 CST 2026
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_user_info_ref.update_time
     *
     * @param updateTime the value for tag_user_info_ref.update_time
     *
     * @mbg.generated Wed Apr 15 15:10:00 CST 2026
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_user_info_ref.is_delete
     *
     * @return the value of tag_user_info_ref.is_delete
     *
     * @mbg.generated Wed Apr 15 15:10:00 CST 2026
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_user_info_ref.is_delete
     *
     * @param isDelete the value for tag_user_info_ref.is_delete
     *
     * @mbg.generated Wed Apr 15 15:10:00 CST 2026
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }
}