package com.taoye.labor_dispatch.entity;

import java.util.Date;

public class UserInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.id
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_name
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.wechat_number
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    private String wechatNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.phone
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.age
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    private Byte age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.nativ_place
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    private String nativPlace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.intention_level
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    private Byte intentionLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.work_attitude
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    private Byte workAttitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.create_time
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.update_time
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.is_delete
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    private Byte isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.id
     *
     * @return the value of user_info.id
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.id
     *
     * @param id the value for user_info.id
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_name
     *
     * @return the value of user_info.user_name
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_name
     *
     * @param userName the value for user_info.user_name
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.wechat_number
     *
     * @return the value of user_info.wechat_number
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    public String getWechatNumber() {
        return wechatNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.wechat_number
     *
     * @param wechatNumber the value for user_info.wechat_number
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    public void setWechatNumber(String wechatNumber) {
        this.wechatNumber = wechatNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.phone
     *
     * @return the value of user_info.phone
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.phone
     *
     * @param phone the value for user_info.phone
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.age
     *
     * @return the value of user_info.age
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    public Byte getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.age
     *
     * @param age the value for user_info.age
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    public void setAge(Byte age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.nativ_place
     *
     * @return the value of user_info.nativ_place
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    public String getNativPlace() {
        return nativPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.nativ_place
     *
     * @param nativPlace the value for user_info.nativ_place
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    public void setNativPlace(String nativPlace) {
        this.nativPlace = nativPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.intention_level
     *
     * @return the value of user_info.intention_level
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    public Byte getIntentionLevel() {
        return intentionLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.intention_level
     *
     * @param intentionLevel the value for user_info.intention_level
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    public void setIntentionLevel(Byte intentionLevel) {
        this.intentionLevel = intentionLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.work_attitude
     *
     * @return the value of user_info.work_attitude
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    public Byte getWorkAttitude() {
        return workAttitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.work_attitude
     *
     * @param workAttitude the value for user_info.work_attitude
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    public void setWorkAttitude(Byte workAttitude) {
        this.workAttitude = workAttitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.create_time
     *
     * @return the value of user_info.create_time
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.create_time
     *
     * @param createTime the value for user_info.create_time
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.update_time
     *
     * @return the value of user_info.update_time
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.update_time
     *
     * @param updateTime the value for user_info.update_time
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.is_delete
     *
     * @return the value of user_info.is_delete
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.is_delete
     *
     * @param isDelete the value for user_info.is_delete
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }
}