package com.taoye.labor_dispatch.entity.dto;

import com.baomidou.mybatisplus.annotation.TableField;

import java.util.Date;
import java.util.List;

/**
 * @author (taoye)  
 * @version V1.0 
 * @ClassName: IntialDescriptionDto 
 * @Description: TODO() 
 * @date 2026-04-14 22:38
 */
public class IntialDescriptionDto {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intial_description.id
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intial_description.intial_description
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    private String intialDescription;


    private Long upstreamLaborCompanyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intial_description.wechat_number
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    private String wechatNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intial_description.create_time
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    private Date createTime;

    private String groupAffiliation;

    private String remark;

    private String createTimeFrom;

    private List<String> tagInfoList;

    private List<Long> ids;
    private String createTimeTo;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intial_description.update_time
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intial_description.is_delete
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    private Byte isDelete;

    private Integer pageNum = 1;   // 默认第1页
    private Integer pageSize = 10;

    public String getWechatName() {
        return wechatName;
    }

    public void setWechatName(String wechatName) {
        this.wechatName = wechatName;
    }

    public String getCompanyName() {
        return companyName;
    }

    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    public String getJobName() {
        return jobName;
    }

    public void setJobName(String jobName) {
        this.jobName = jobName;
    }

    public Byte getJobType() {
        return jobType;
    }

    public void setJobType(Byte jobType) {
        this.jobType = jobType;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getContact() {
        return contact;
    }

    public void setContact(String contact) {
        this.contact = contact;
    }

    public String getWelfare() {
        return welfare;
    }

    public void setWelfare(String welfare) {
        this.welfare = welfare;
    }

    public String getRequirement() {
        return requirement;
    }

    public void setRequirement(String requirement) {
        this.requirement = requirement;
    }

    public String getDuty() {
        return duty;
    }

    public void setDuty(String duty) {
        this.duty = duty;
    }

    public String getEducation() {
        return education;
    }

    public void setEducation(String education) {
        this.education = education;
    }

    public String getExperience() {
        return experience;
    }

    public void setExperience(String experience) {
        this.experience = experience;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public String getSalary() {
        return salary;
    }

    public void setSalary(String salary) {
        this.salary = salary;
    }

    /**
     * 微信号
     */
    @TableField("wechat_name")
    private String wechatName;

    /**
     * 公司名
     */
    @TableField("company_name")
    private String companyName;

    /**
     * 岗位名称
     */
    @TableField("job_name")
    private String jobName;

    /**
     * 薪资范围
     */
    @TableField("salary")
    private String salary;

    /**
     * 工作地点，多个逗号分隔
     */
    @TableField("location")
    private String location;

    /**
     * 经验要求
     */
    @TableField("experience")
    private String experience;

    /**
     * 学历要求
     */
    @TableField("education")
    private String education;

    /**
     * 岗位职责
     */
    @TableField("duty")
    private String duty;

    /**
     * 任职要求
     */
    @TableField("requirement")
    private String requirement;

    /**
     * 福利待遇
     */
    @TableField("welfare")
    private String welfare;

    /**
     * 联系人
     */
    @TableField("contact")
    private String contact;

    /**
     * 联系电话
     */
    @TableField("phone")
    private String phone;

    /**
     * 类型：1日结 2小时工 3工作介绍 4进厂
     */
    @TableField("job_type")
    private Byte jobType;

    public IntialDescriptionDto() {
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intial_description.id
     *
     * @return the value of intial_description.id
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intial_description.id
     *
     * @param id the value for intial_description.id
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intial_description.intial_description
     *
     * @return the value of intial_description.intial_description
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    public String getIntialDescription() {
        return intialDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intial_description.intial_description
     *
     * @param intialDescription the value for intial_description.intial_description
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    public void setIntialDescription(String intialDescription) {
        this.intialDescription = intialDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intial_description.wechat_number
     *
     * @return the value of intial_description.wechat_number
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    public String getWechatNumber() {
        return wechatNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intial_description.wechat_number
     *
     * @param wechatNumber the value for intial_description.wechat_number
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    public void setWechatNumber(String wechatNumber) {
        this.wechatNumber = wechatNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intial_description.create_time
     *
     * @return the value of intial_description.create_time
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intial_description.create_time
     *
     * @param createTime the value for intial_description.create_time
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intial_description.update_time
     *
     * @return the value of intial_description.update_time
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intial_description.update_time
     *
     * @param updateTime the value for intial_description.update_time
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intial_description.is_delete
     *
     * @return the value of intial_description.is_delete
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intial_description.is_delete
     *
     * @param isDelete the value for intial_description.is_delete
     *
     * @mbg.generated Tue Apr 14 22:10:20 CST 2026
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }

    public String getCreateTimeFrom() {
        return createTimeFrom;
    }

    public void setCreateTimeFrom(String createTimeFrom) {
        this.createTimeFrom = createTimeFrom;
    }

    public void setCreateTimeTo(String createTimeTo) {
        this.createTimeTo = createTimeTo;
    }

    public String getCreateTimeTo() {
        return createTimeTo;
    }

    public String getGroupAffiliation() {
        return groupAffiliation;
    }

    public void setGroupAffiliation(String groupAffiliation) {
        this.groupAffiliation = groupAffiliation;
    }

    public List<String> getTagInfoList() {
        return tagInfoList;
    }

    public void setTagInfoList(List<String> tagInfoList) {
        this.tagInfoList = tagInfoList;
    }

    public Integer getPageNum() {
        return pageNum;
    }

    public void setPageNum(Integer pageNum) {
        this.pageNum = pageNum;
    }

    public Integer getPageSize() {
        return pageSize;
    }

    public void setPageSize(Integer pageSize) {
        this.pageSize = pageSize;
    }

    public List<Long> getIds() {
        return ids;
    }

    public void setIds(List<Long> ids) {
        this.ids = ids;
    }

    public Long getUpstreamLaborCompanyId() {
        return upstreamLaborCompanyId;
    }

    public void setUpstreamLaborCompanyId(Long upstreamLaborCompanyId) {
        this.upstreamLaborCompanyId = upstreamLaborCompanyId;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }
}
